# -*- coding: utf-8 -*-
"""从 export_madmom_ir.py 产出的 ir.json 生成纯 C# 前向引擎所需的图描述数据（MadmomIr.g.cs）。

产物：Madmom/MadmomIr.g.cs
  - 算子常量（与 IrGraph 0..25 一致）
  - 缓冲区元数据（元素数 / 形状，时间维以 1 占位，引擎运行时替换为真实 T）
  - 节点表（算子 / 输入 / 输出 / 属性）
  - 命名权重（RNN/Dense，base64 内联；运行时解码为 float[] 填入 IrGraph.Weights）
  - Build()：构造 IrGraph 并注入 InputFeatureDim / OutputDim / Fps / OutputBuffer

这样 C# 侧无需任何 JSON 解析或外部依赖，桌面/Unity 通用。

用法：python gen_madmom_cs.py [--ir OUT/ir.json] [--out Madmom/MadmomIr.g.cs]
"""
import base64
import json
import os

import numpy as np

OUT_DIR = os.path.join(os.path.dirname(__file__), "out")
CS_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "Madmom", "MadmomIr.g.cs")

# 算子编码（必须与 C# 侧 IrGraph 常量一致）
OPS = ["Reshape", "Slice", "Pad", "Unsqueeze", "Conv", "Neg", "Transpose", "Concat",
       "Mul", "ReduceSum", "Sqrt", "Add", "Log", "ReduceMin", "Sub", "ReduceMax",
       "Div", "Equal", "Where", "Relu", "Sigmoid", "Lstm", "Gru", "Blstm",
       "Dense", "Tanh", "Softmax"]
OPC = {o: i for i, o in enumerate(OPS)}


def emit_ints(name, vals, per_line=20):
    out = ["    public static readonly int[] %s = new int[%d]" % (name, len(vals))]
    out[0] += "\n    {\n"
    for i in range(0, len(vals), per_line):
        chunk = ", ".join(str(int(v)) for v in vals[i:i + per_line])
        out.append("        " + chunk + ",\n")
    out.append("    };\n")
    return "".join(out)


def emit_bytes(name, vals, per_line=30):
    out = ["    public static readonly byte[] %s = new byte[%d]" % (name, len(vals))]
    out[0] += "\n    {\n"
    for i in range(0, len(vals), per_line):
        chunk = ", ".join(str(int(v)) for v in vals[i:i + per_line])
        out.append("        " + chunk + ",\n")
    out.append("    };\n")
    return "".join(out)


def prod(shape):
    p = 1
    for x in shape:
        p *= int(x)
    return p


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", default=os.path.join(OUT_DIR, "ir.json"),
                    help="导出的 ir.json 路径")
    ap.add_argument("--cs", default=CS_PATH,
                    help="输出的 C# 文件路径（默认 Madmom/MadmomIr.g.cs）")
    ap.add_argument("--class-name", default="MadmomIr",
                    help="生成的 C# 类名（默认 MadmomIr）")
    args = ap.parse_args()
    ir = json.load(open(args.ir, encoding="utf-8"))
    CS_PATH_LOCAL = args.cs
    CLASS = args.class_name
    meta = ir["meta"]
    nbuffers = meta["nBuffers"]
    bshape = {int(k): [int(x) for x in v] for k, v in ir["bufferShapes"].items()}

    # ---- 命名权重（RNN/Dense）----
    named = ir["namedWeights"]
    named_names = sorted(named.keys())
    named_decoded = {nm: np.frombuffer(base64.b64decode(named[nm]["b64"]), dtype=np.float32)
                     for nm in named_names}

    # ---- 节点表 ----
    op_arr, in0, in1, in2, out_arr = [], [], [], [], []
    list_data, list_off = [], [0]
    for n in ir["nodes"]:
        op = n["op"]
        assert op in OPC, op
        op_arr.append(OPC[op])
        out_arr.append(int(n["outs"][0]))
        ins = list(n["ins"]) + [-1] * (3 - len(n["ins"]))
        for pos in range(3):
            v = ins[pos]
            if v is None:
                v = -1
            (in0 if pos == 0 else in1 if pos == 1 else in2).append(int(v))
        lst = [int(x) for x in n.get("list", [])]
        list_data += lst
        list_off.append(len(list_data))

    # ---- 缓冲区元数据（时间维以 1 占位）----
    buf_count, buf_rank, shape_data, shape_off = [], [], [], []
    for b in range(nbuffers):
        shp = bshape[b]
        buf_count.append(prod(shp))
        buf_rank.append(len(shp))
        shape_off.append(len(shape_data))
        shape_data.extend(shp)
    shape_off.append(len(shape_data))

    # 无 CNN 常量权重（madmom RNN 模型为空）→ 全空
    w_off, w_cnt, w_rank, w_shpdata, w_shapeoff, wdata = [], [], [], [], [], np.zeros(0, np.float32)
    w_shapeoff.append(0)

    src = []
    src.append("// <auto-generated>\n")
    src.append("// 由 .madmom_export/gen_madmom_cs.py 从 madmom 模型导出，请勿手工修改。\n")
    src.append("// 内容：常量折叠后的前向图描述 + 命名权重（RNN/Dense）。\n")
    src.append("using System;\nusing System.Collections.Generic;\n\n")
    src.append("namespace Madmom;\n\n")
    src.append("/// <summary>\n")
    src.append("/// madmom（downbeat/beat）常量折叠后的前向图描述 + 命名权重（由 export_madmom_ir.py 生成）。\n")
    src.append("/// 桌面引擎（MadmomEngine）与 Unity 移植共用同一份数据。\n")
    src.append("/// </summary>\n")
    src.append("public static class %s\n{\n" % CLASS)
    src.append("    // ---- 算子编码 ----\n")
    for i, o in enumerate(OPS):
        src.append("    public const byte %s = %d;\n" % (o, i))
    src.append("\n    public const int NBuffers = %d;\n" % nbuffers)
    src.append("    public const int NNodes = %d;\n" % len(op_arr))
    src.append("    public const int NWeights = %d;\n\n" % len(wdata))

    src.append("    // ---- 图输入 / 输出缓冲区 ----\n")
    src.append("    public const int InputBuffer = %d;\n" % meta["inputBuffer"])
    src.append("    public const int OutputBuffer = %d;  // 模型最终输出缓冲区\n" % meta["outputBuffer"])
    src.append("    public const int InputFeatureDim = %d;  // 输入特征维（第一层权重决定）\n" % meta["inputFeatureDim"])
    src.append("    public const int OutputDim = %d;  // 输出维（downbeat=3 / beat=1）\n" % meta["outputDim"])
    src.append("    public const double Fps = %s;  // 特征帧率\n\n" % repr(float(meta["fps"])))

    src.append("    // ---- 缓冲区元数据（元素数 / 形状，时间维以 1 占位）----\n")
    src.append(emit_ints("BufferCount", buf_count))
    src.append(emit_ints("BufferRank", buf_rank))
    src.append(emit_ints("ShapeOff", shape_off))
    src.append(emit_ints("ShapeData", shape_data))
    src.append("\n    // ---- 节点表 ----\n")
    src.append("    // 输入编码：>=0 缓冲区索引；-1 缺省\n")
    src.append(emit_bytes("Op", op_arr))
    src.append(emit_ints("In0", in0))
    src.append(emit_ints("In1", in1))
    src.append(emit_ints("In2", in2))
    src.append(emit_ints("Out", out_arr))
    src.append("    // 变长属性：节点 i 的属性 = List[ListOff[i] .. ListOff[i+1]]\n")
    src.append(emit_ints("ListOff", list_off))
    src.append(emit_ints("List", list_data))
    src.append("\n    // ---- CNN 常量权重张量（madmom RNN 模型通常为空）----\n")
    src.append(emit_ints("WeightOff", w_off))
    src.append(emit_ints("WeightCount", w_cnt))
    src.append(emit_ints("WeightRank", w_rank))
    src.append(emit_ints("WeightShapeOff", w_shapeoff))
    src.append(emit_ints("WeightShapeData", w_shpdata))
    src.append("    public static readonly float[] WeightData = new float[0];\n")

    # ---- 命名权重（RNN/Dense）----
    src.append("\n    // ---- 命名权重（RNN/Dense），base64 内联，运行时解码 ---- \n")
    # 解码辅助
    src.append("    private static float[] _B64(string s)\n    {\n")
    src.append("        var bytes = Convert.FromBase64String(s);\n")
    src.append("        var f = new float[bytes.Length / 4];\n")
    src.append("        Buffer.BlockCopy(bytes, 0, f, 0, bytes.Length);\n")
    src.append("        return f;\n    }\n")
    for nm in named_names:
        arr = named_decoded[nm]
        b64 = base64.b64encode(np.ascontiguousarray(arr, dtype=np.float32).tobytes()).decode()
        field = "W_" + "".join(ch if ch.isalnum() else "_" for ch in nm)
        src.append('    private const string %s_B64 =\n' % field)
        for i in range(0, len(b64), 100):
            src.append('        "%s" +\n' % b64[i:i + 100])
        src.append('        "";\n')
        src.append("    public static readonly float[] %s = _B64(%s_B64);\n" % (field, field))

    src.append("\n    /// <summary>构造 IrGraph 实例（含命名权重与元数据）。</summary>\n")
    src.append("    public static IrGraph Build()\n    {\n")
    src.append("        var weights = new Dictionary<string, float[]>\n        {\n")
    for nm in named_names:
        field = "W_" + "".join(ch if ch.isalnum() else "_" for ch in nm)
        src.append('            { "%s", %s },\n' % (nm, field))
    src.append("        };\n")
    src.append("        var g = new IrGraph(NBuffers, NNodes, NWeights, InputBuffer,\n")
    src.append("            BufferCount, BufferRank, ShapeOff, ShapeData,\n")
    src.append("            Op, In0, In1, In2, Out, ListOff, List,\n")
    src.append("            WeightOff, WeightCount, WeightRank, WeightShapeOff, WeightShapeData, WeightData,\n")
    src.append("            weights);\n")
    src.append("        g.InputFeatureDim = InputFeatureDim;\n")
    src.append("        g.OutputDim = OutputDim;\n")
    src.append("        g.Fps = Fps;\n")
    src.append("        g.OutputBuffer = OutputBuffer;\n")
    src.append("        return g;\n    }\n")
    src.append("}\n")

    with open(CS_PATH_LOCAL, "w", encoding="utf-8") as f:
        f.write("".join(src))

    print("节点数:", len(op_arr), " 缓冲区:", nbuffers)
    print("命名权重数:", len(named_names), " 总参数:", int(sum(a.size for a in named_decoded.values())))
    print("已写入:", CS_PATH_LOCAL)


if __name__ == "__main__":
    main()
